language: cpp
notifications:
  email: false
sudo: true

before_install:
 - curl -sLO https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb && sudo dpkg -i devkitpro-pacman.deb && rm devkitpro-pacman.deb
 - sudo dkp-pacman --sync --noconfirm $(sudo dkp-pacman -Ssq switch-*)
 - sudo pip install cmake
 - mkdir /opt/libtransistor/
 - curl -sLO https://github.com/reswitched/libtransistor/releases/download/v2.1.1/libtransistor_v2.1.1.tar.gz && tar xf libtransistor_v2.1.1.tar.gz -C /opt/libtransistor && rm libtransistor_v2.1.1.tar.gz
script:
 - source /etc/profile.d/devkit-env.sh && make
